version: '3'
services:
    simple_blog_api:
        depends_on:
            - postgres_db
        build:
            context: .
            dockerfile: Dockerfile.prod
        image: 'rajshekar0495/simpleblog_api'
        ports:
            - '3000:3000'
        environment: 
            - POSTGRES_HOST=postgres_db
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    postgres_db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
           